### PR TITLE
feat: add explain code prompt option

### PR DESCRIPTION
**Pull request by pengx17**
fix https://github.com/yetone/openai-translator/issues/89

not really something that should be included in a normal translator, but I guess this is useful for coders 😂

One possible solution is to allow users to customize prompts. Another option is to provide a set of predefined actions, but limit the user's selection to a maximum of four.

image

### CODE REVIEW

**Comment by yetone** [comment]
Very Cool! Thanks!

**Comment by LuciNyan** [comment]
Awesome! 😍

**Comment by yetone** [comment]
LGTM! Thank you!

**Comment by est7** [comment]
@yetone @pengx17 感谢您们的付出,就是能不能顺便也给bob加上这个feat.....

**Pull request merged**
