### PR TITLE
feat: upload image to translation with OCR

### PR DESCRIPTION
**Pull request by okisdev**
# Description
- [x] Allow the user to upload the image (1 MB limit)
- [x] OCR image (English, Simplified Chinese, Traditional Chinese, Japanese, Russian) 

# Demo
CleanShot_2023-03-11_07 24 52@2x

CleanShot_2023-03-11_07 25 13

## Chinese
CleanShot_2023-03-11_01 14 45@2x 

CleanShot_2023-03-11_07 26 31@2x

## English
CleanShot_2023-03-11_00 38 49@2x

CleanShot_2023-03-11_07 30 05@2x

## Japanese
CleanShot_2023-03-11_00 50 22@2x

CleanShot_2023-03-11_07 28 53@2x

## Russian
CleanShot_2023-03-11_01 19 34@2x

CleanShot_2023-03-11_07 28 17@2x

### CODE REVIEW

**Comment by yetone** [comment]
Wow!!! Soooooooo COOL!

**Comment by yetone** [comment]
Great Job! The upload button is a bit too big and doesn't look coordinated. Can it be placed in the bottom right corner next to TTS as an OCR button?

**Comment by okisdev** [comment]
@yetone try it again now.

**Comment by yetone** [comment]
LGTM!

**Pull request merged**
