### PR TITLE
feat: show notification when IP not supported

### PR DESCRIPTION
**Pull request by OverflowCat**
image

By the way, `dev-`/`build-` `browser-extension` seems broken, and I cannot test browser extension.

### CODE REVIEW

**Comment by yetone** [comment]
LGTM!

**Comment by OverflowCat** [comment]
And how to bypass the spell checker?

```sh
$ typos . --config ./typos.toml
Warning: "BA" should be "BY" or "BE".
error: `BA` should be `BY`, `BE`
  --> ./src/common/geo.ts:55:6
   |
55 |     'BA',
   |      ^^
   |
Error: Process completed with exit code 2.
```

**Comment by OverflowCat** [comment]
> Very strange, it is ok on my side
> 
> image

```powershell
find dist/* -not -path "dist/userscript*" -prune -exec rm -rf {} \;
sed -i -e "s/\"version\": \".*\"/\"version\": \"0.1.0\"/" public/manifest.json
sed -i -e "s/\"version\": \".*\"/\"version\": \"0.1.0\"/" public/manifest.firefox.json
sed -i -e "s/\"version\": \".*\"/\"version\": \"0.1.0\"/" src-tauri/tauri.conf.json
sed -i -e "s/\"version\": \".*\"/\"version\": \"0.1.0\"/" package.json
sed -i -e "s/\/\/ @version.*/\/\/ @version 0.1.0/" public/userscript.js
sed -i.js-e -E 's|openai-translator@[^/]+|openai-translator@v0.1.0|g' public/userscript.js
process_begin: CreateProcess(NULL, sed -i.js-e -E s|openai-translator@[^/]+|openai-translator@v0.1.0|g public/userscript.js, ...) failed.
make (e=2): ?μí3?ò2?μ????¨μ????t?￡
make: *** [makefile:12: change-version] Error 2
PS E:\code\openai-translator> 
```

Maybe caused by the `sed -i.js-e`?

**Comment by yetone** [comment]
> > Very strange, it is ok on my side
> > image
> 
> ```powershell
> find dist/* -not -path "dist/userscript*" -prune -exec rm -rf {} \;
> sed -i -e "s/\"version\": \".*\"/\"version\": \"0.1.0\"/" public/manifest.json
> sed -i -e "s/\"version\": \".*\"/\"version\": \"0.1.0\"/" public/manifest.firefox.json
> sed -i -e "s/\"version\": \".*\"/\"version\": \"0.1.0\"/" src-tauri/tauri.conf.json
> sed -i -e "s/\"version\": \".*\"/\"version\": \"0.1.0\"/" package.json
> sed -i -e "s/\/\/ @version.*/\/\/ @version 0.1.0/" public/userscript.js
> sed -i.js-e -E 's|openai-translator@[^/]+|openai-translator@v0.1.0|g' public/userscript.js
> process_begin: CreateProcess(NULL, sed -i.js-e -E s|openai-translator@[^/]+|openai-translator@v0.1.0|g public/userscript.js, ...) failed.
> make (e=2): ?μí3?ò2?μ????¨μ????t?￡
> make: *** [makefile:12: change-version] Error 2
> PS E:\code\openai-translator> 
> ```
> 
> Maybe caused by the `sed -i.js-e`?

Maybe, you can modify this line and try it again.

**Comment by yetone** [comment]
You can use `extend-words`: https://github.com/crate-ci/typos#false-positives

**Comment by paicha** [comment]
This notification keeps popping up, it's a bit annoying. It should be closed and not displayed again.

**Comment by OverflowCat** [comment]
> This notification keeps popping up, it's a bit annoying. It should not be displayed again after the user closes it.

@paicha This feature can prove useful, especially for users who frequently change their network environment. We use OpenAI's official API to ensure that there are no false positives when this red notification appears. So, the red notification won't disappear until you change your network configuration. This is by design as people do get banned by OpenAI in such situation.

A yellow notification, however, indicates that OpenAI is currently inaccessible. If you encounter the latter one and are sure that your network connection is functioning correctly, then it may be a bug and sbould be reported.

**Comment by paicha** [comment]
> > This notification keeps popping up, it's a bit annoying. It should not be displayed again after the user closes it.
> 
> @paicha This feature can prove useful, especially for users who frequently change their network environment. We use OpenAI's official API to ensure that there are no false positives when this red notification appears. So, the red notification won't disappear until you change your network configuration. This is by design as people do get banned by OpenAI in such situation.
> 
> A yellow notification, however, indicates that OpenAI is currently inaccessible. If you encounter the latter one and are sure that your network connection is functioning correctly, then it may be a bug and sbould be reported.

Being banned by OpenAI due to the use of an unsupported regional IP address is just a speculation. Personally, I have been using a Hong Kong IP address for several months without encountering any account bans.

Your concern is reasonable, but user choice should be respected. It's like turning off vehicle speed limit warnings - we choose to believe that users know what they're doing.

Another possible scenario is that if the user is using a third-party proxy API, this warning may be unnecessary.

**Pull request merged**
