### PR TITLE
feat: add browser shortcuts (#163,#6)

### PR DESCRIPTION
**Pull request by kinfuy**
Browser plugin supports shortcut key wake-up
fix The scroll bar appears and its position is inaccurate

fix: #163 #6

### CODE REVIEW

**Comment by yetone** [comment]
LGTM! Thanks for your contribution!

**Comment by yetone** [comment]
This approach is not working now?

https://github.com/yetone/openai-translator/blob/649a9d0b0195064dc78661d227e4a8362c5aabab/src/content_script/index.tsx#L205

**Comment by kinfuy** [comment]
> This approach is not working now?
> 
> https://github.com/yetone/openai-translator/blob/649a9d0b0195064dc78661d227e4a8362c5aabab/src/content_script/index.tsx#L205

I'm sorry I may not have noticed this way

**Comment by kinfuy** [comment]
However, this input method may be inconvenient. It would be great if there were automatic recognition key input

**Pull request closed without merging**
