### PR TITLE
Dark Mode Support

### PR DESCRIPTION
**Pull request by tywtyw2002**
Add Dark theme support, auto switch by OS settings.

Color base on `baseui` theme.

Snipaste_2023-03-14_22-26-05

Snipaste_2023-03-14_22-27-24

Snipaste_2023-03-14_22-27-38

### CODE REVIEW

**Comment by yetone** [comment]
LGTM!

**Comment by yetone** [comment]
Sorry, you should fix the conflicts

**Comment by tywtyw2002** [comment]
fixed

**Comment by yetone** [comment]
Great job! Thanks!

**Pull request merged**
