### PR TITLE
Support installing OpenAITranslator from winget

### PR DESCRIPTION
**Pull request by igoogolx**
Through the [PR](https://github.com/microsoft/winget-pkgs/pull/99321),  OpenAI Translator has been added to Winget. Windows users can now install it by executing the following command:

```sh
winget install yetone.OpenAITranslator
```

To better support Winget, we can integrate it into GitHub Actions. After that, once a new version is released, CI will automatically update that to Winget. Before merging this PR, please follow these steps:

1. Please add a GitHub token with public_repo and workflow scopes as a repository secret and rename the secret name to "WINGET_TOKEN" in the workflow.
2. Fork [microsoft/winget-pkgs](https://github.com/microsoft/winget-pkgs) under @yetone 

See [more info](https://github.com/vedantmgoyal2009/winget-releaser) about winget action.

### CODE REVIEW

**Comment by yetone** [comment]
LGTM! Thanks!

**Comment by yetone** [comment]
Great job!

**Comment by IlluminateDarkheat** [comment]
winget只能下载到0.0.20版本，检测不到更新的版本。

> winget install yetone.OpenAITranslator
> 找到已安装的现有包。正在尝试升级已安装的包...
> 找不到适用的升级。

> winget show yetone.OpenAITranslator
> 已找到 OpenAI Translator [yetone.OpenAITranslator]
> 版本: 0.0.20
> 发布者: yetone
> 描述: Browser extension and cross-platform desktop application for translation based on ChatGPT API.
> 许可证: AGPL-3.0 License
> 安装：
>    安装程序类型： wix
>    安装程序区域设置： en-US
>    安装程序 URL： https://github.com/yetone/openai-translator/releases/download/v0.0.20/OpenAI.Translator_0.0.20_x64_en-US.msi
>    安装程序 SHA256： 716252f8a4011e7af717c9a8416e8bd62d22ef2fa111a15d00c66c18db630ae4

**Comment by igoogolx** [comment]
需要等待新版本的 [PR](https://github.com/microsoft/winget-pkgs/pull/99434) 合并

**Pull request merged**
