### PR TITLE
Add ChatGPT Web API as backend

### PR DESCRIPTION
**Pull request by tengattack**
Use ChatGPT Web API as backend (need sign in first)

BTW, fix `backgroundFetch` has no resolve after the request end.

image

### CODE REVIEW

**Comment by yetone** [comment]
So COOOOOOOOOOOL! LGTM!

**Comment by tengattack** [comment]
It seems the CI does not run automatically

**Comment by yetone** [comment]
@tengattack Thanks for your contribution! Now it should be able to run CI automatically.

**Comment by yetone** [comment]
@tengattack Have you encountered the following Cloudflare issues?

image

**Comment by tengattack** [comment]
> @tengattack Have you encountered the following Cloudflare issues?
> 
> image

You mean the ChatGPT web access limitation?

**Comment by tengattack** [comment]
The CI pipelines need approval now :)

**Comment by yetone** [comment]
`yarn lint --fix` may help you

**Comment by tengattack** [comment]
I have a custom routing policy, and configure `*.openai.com` as a single rule there, I think there is no way to bypass the access limit.

**Comment by tengattack** [comment]
> `yarn lint --fix` may help you

Sorry for my poor text editor, it works now

**Comment by yetone** [comment]
Sorry, my IP is blocked by ChatGPT, I can't verify this PR for now, I'm trying to figure out how to fix it.

**Comment by douglarek** [comment]
Verified on Firefox and Edge, works well. Thank you.

**Comment by nanvon** [comment]
@yetone Hello author, may I ask if the plugin version that supports ChatGPT Web API has been updated? Is there a plan for an update? I'm really looking forward to this feature.

**Comment by douglarek** [comment]
> @yetone Hello author, may I ask if the plugin version that supports ChatGPT Web API has been updated? Is there a plan for an update? I'm really looking forward to this feature.

The latest code has been merged into the main branch, but a new version has not been released yet, so we need to wait.

**Comment by szh-bash** [comment]
> @yetone Hello author, may I ask if the plugin version that supports ChatGPT Web API has been updated? Is there a plan for an update? I'm really looking forward to this feature.

Has been released today

**Comment by JDYG** [comment]
image
I can not find the Chatgpt web option on the new version (0.0.40). How to find the entrance for the web version?

**Comment by douglarek** [comment]
> image I can not find the Chatgpt web option on the new version (0.0.40). How to find the entrance for the web version?

ChatGPT web only works as a browser extension.

**Pull request merged**
